---

apiVersion: v1
kind: Namespace
metadata:
  name: student-apis
  labels:
    app: student-apis

---

# Service for Application
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-apis
  labels:
    app: student-api
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
  selector:
    app: student-api
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-apis
  labels:
    app: student-api
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - database

      containers:
      - name: student-api
        image: flickerbot/student:testv1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_HOST
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: FLASK_HOST
        - name: FLASK_PORT
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: FLASK_PORT
        - name: RUN_MIGRATIONS
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: RUN_MIGRATIONS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: DATABASE_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: MYSQL_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: MYSQL_DATABASE


