---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: student-apis
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-apis
  labels:
    app: student-api
data:
  # Server configuration
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  FLASK_APP: "student.py"
  
  # MySQL Database configuration
  MYSQL_HOST: "db"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "student_db"
  
  # Migration control
  RUN_MIGRATIONS: "true"

--- 


apiVersion: v1
kind: Secret
metadata:
  name: student-api-secrets
  namespace: student-apis
  labels:
    app: student-api
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "password"
  DATABASE_URL: "mysql://admin:password@db:3306/student_db"
  #DATABASE_URL: "mysql://admin:password@db.student-apis.svc.cluster.local:3306/student_db"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: student-apis
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        args:
        - "--bind-address=0.0.0.0"
        ports:
        - containerPort: 3306
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-api-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: MYSQL_DATABASE

