apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app: vault

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.19
          args:
            - "server"
            - "-dev"
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                listener "tcp" {
                  address = "0.0.0.0:8201"
                  tls_disable = 1
                }

                storage "file" {
                  path = "/vault/data"
                }

                disable_mlock = true

                ui = true
                api_addr = "http://vault.vault.svc:8201"
          ports:
            - containerPort: 8201
              name: http
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: vault-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8201
      targetPort: 8201
