apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets # ClusterSecretStore can live in the ESO namespace
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8201"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
    
--- 
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
stringData:
  token: "<root_token for vault>"   
---