# Deploy services running on Docker Compose 
deploy:
	@echo "Deploying services..."
	docker compose up -d


# Check status of running containers 
status:
	@echo "Checking container status..."
	docker compose ps

# View logs
logs:
	@echo "Showing logs..."
	docker compose logs -f

# setup env file in virtialbox
env:
	cp .env.example .env;


