# Deploy services running on Docker Compose 
deploy:
	@echo "Deploying services..."
	docker compose up -d


# Check status of running containers 
status:
	@echo "Checking container status..."
	docker compose ps

# View logsS
logs:
	@echo "Showing logs..."
	docker compose logs -f


