name: CI for Milestone 4

on:
  push:
    branches: [ milestone4 ]
  pull_request:
    branches: [ milestone4 ]

jobs:
  build:
    runs-on: self-hosted
    #this lets us to run github on self-hosted machine, if we are using github workflows we can use ubuntu-latest here 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      #checking out the latest code it will check the SHA tag where this request was created 
      
    - name: Run setup
      working-directory: ./milestone4
      run: make setup
      # installing the necessary dependencies for pylint or tetsing 
      
    - name: Run tests
      working-directory: ./milestone4
      run: make test
      # running the tests, refer makefile if wanna know what this command do 
      
    - name: Perform code linting with pylint
      working-directory: ./milestone4
      run: make lint
      # running tcode linting using pylint 
      
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # - name: Docker build
    #   working-directory: ./milestone4
    #   run: make docker-build