name: CI for Milestone 4

on:
  push:
    branches: [ milestone4 ]
  pull_request:
    branches: [ milestone4 ]

  workflow_dispatch:  # Allows manual triggering of the workflow



jobs:
  build:
    runs-on: self-hosted
    env:  
    DOCKER_TAG: ${{ github.sha }}
    #this lets us to run github on self-hosted machine, if we are using github workflows we can use ubuntu-latest here 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #checking out the latest code it will check the SHA tag where this request was created 
     
    - name: setup
      working-directory: milestone4
      run: make setup
     
    - name: env
      working-directory: milestone4
      run: make env

    - name: Run tests
      working-directory: milestone4
      run: make test
      # running the tests, refer makefile if wanna know what this command do 
      
    - name: Perform code linting with pylint
      working-directory: milestone4
      run: make lint
      # running tcode linting using pylint 
      
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker build
      working-directory: milestone4
      run: make docker-build DOCKER_TAG: ${{ github.sha }}