name: CI for Milestone 4

on:
  push:
    paths: [ student.py ]
    branches: [ milestone4 ]
  pull_request:
    paths: [student.py ]
    branches: [ milestone4 ]

  workflow_dispatch:  # Allows manual triggering of the workflow



jobs:
  build:
    runs-on: self-hosted
       #this lets us to run github on self-hosted machine, if we are using github workflows we can use ubuntu-latest here 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #checking out the latest code it will check the SHA tag where this request was created 
     
    - name: setup
      working-directory: milestone4
      run: make setup
     
    - name: env
      working-directory: milestone4
      run: make env

  test:
    runs-on: self-hosted
    needs: build  # Make sure setup is completed before running test
    steps:
    - name: Run tests
      working-directory: milestone4
      run: make test
      # running the tests, refer makefile if wanna know what this command do 

  linting:
    runs-on: self-hosted
    needs: build # Ensure setup is done before linting 
    steps:
    - name: Perform code linting with pylint
      working-directory: milestone4
      run: make lint
      # running tcode linting using pylint 
      
  docker-login:
    runs-on: self-hosted
    needs: [build, linting,test]  # Ensure setup and linting are done before docker build
    env:  
      DOCKER_TAG: ${{ github.sha }}
      #passing custome tag in the env, that will be passed as tag to dockerhub 


    steps:
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # Logging into the dockerhub, secrets will be detched form the github secrets 
        
    - name: Docker build
      working-directory: milestone4
      run: make docker-build DOCKER_TAG=$DOCKER_TAG
      # Building the Docker image with the generated tag